//! **Mutations**: the typed server round-trip, expressed as effects-as-messages.
//!
//! The client never mutates state it owns — the server's data source is the source of
//! truth, and the loop asks it to change. The mechanics follow the framework's one rule
//! for effects: *commands out, messages in*. [`Ctx::<Live>::mutate`](crate::Ctx::mutate)
//! emits a `ServerRequest` command into the live's ordinary output stream; the browser
//! runtime performs the fetch (`POST /__idyll/m/<hash>`) and hands the response back
//! through the component's `deliver` export, which resolves it to a **message** in the
//! calling component's inbox. The loop stays pure — no futures suspended on the network,
//! no hidden effect handles — and the message log alone reconstructs what happened.
//!
//! A mutation is a **persisted operation** like a query: `mutation!` validates it
//! against the published schema, canonicalizes it (mutation name + args + response
//! selection), and the content hash — an [`OpHash`] — is the only thing the client ever
//! sends. The server executes only artifacts from its boot-validated registry, masks
//! the handler's node to the artifact's recorded selection, and the typed response
//! projection rides back. Serde at both boundaries — parse, don't validate.

pub use idyll_schema::OpHash;

/// A persisted mutation operation, generated by `mutation!`: its identity, its typed
/// variables, and its response projection (the selection's fields, schema-typed).
pub trait Mutation: 'static {
    /// The operation's persisted identity (the artifact's content-hash prefix).
    fn op_hash() -> OpHash;

    /// The operation's input variables (`<Name>Vars`).
    type Vars: serde::Serialize;

    /// What the masked response deserializes as (`<Name>Response` — exactly the
    /// selection's fields).
    type Response: serde::de::DeserializeOwned + 'static;
}

/// A persisted query operation, generated by `query!`: its identity is all the
/// navigation capability needs — [`Turn::navigate`](crate::Ctx::navigate) refires the
/// artifact for a new path and the response replays into the context store.
pub trait Query: 'static {
    /// The operation's persisted identity (the artifact's content-hash prefix).
    fn op_hash() -> OpHash;
}

/// Why a mutation failed — each stage of the round trip refuses with its own
/// variant, so a boundary (or a test) matches the kind instead of parsing prose.
/// Failure faults the live; success never arrives as a message at all (the refresh
/// seed absorbs into the store).
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum MutationError {
    /// The typed variables refused to serialize — an app bug caught before anything
    /// crossed the wire.
    Vars(String),
    /// The round trip failed: transport, or the server refusing.
    Request(crate::driver::RequestError),
    /// The response arrived but wasn't the envelope the contract promises.
    Decode(String),
}

impl std::fmt::Display for MutationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MutationError::Vars(detail) => {
                write!(f, "mutation vars must serialize: {detail}")
            }
            MutationError::Request(err) => write!(f, "mutation failed: {err}"),
            MutationError::Decode(detail) => {
                write!(f, "mutation response decode: {detail}")
            }
        }
    }
}

impl std::error::Error for MutationError {}

/// A failed navigation refetch — the round trip refused (a path the route itself
/// refuses never gets here: the browser falls back to a document navigation
/// instead). Faults the live exactly like a mutation failure.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct NavigateError(pub crate::driver::RequestError);

impl std::fmt::Display for NavigateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "navigation failed: {}", self.0)
    }
}

impl std::error::Error for NavigateError {}
